### PR TITLE
Merge development into ncEngine

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by mikestillman** [comment]
@mahrud Thanks!

What changes did you make on top of development, to get this to compile (oops, I see, it is commit c0c6e49)?  

Also, the changes to monomial orderings code were a real conflict, how did you fix that?  (When I look, I don't see any mention of changes to monordering.cpp, hpp, which are needed by unit tests).  However, @moorewf, I'll look at this, and then if there isn't any other issue, I suggest we merge it and fix the problems from there.  Sound ok?

**Comment by moorewf** [comment]
That sounds good to me!  I'm looking to work on this over break.  In particular, I want to get as much of DGAlgebras as possible running on the new system in a new DGAlgebras2 package which doesn't use bergman.

**Comment by mahrud** [comment]
> What changes did you make on top of development, to get this to compile (oops, I see, it is commit [c0c6e49](https://github.com/moorewf/M2-frank/commit/c0c6e4971bdd64b37d0340c7ef826f2007d0acdb))?

That commit is all the extra changes I needed to make after fixing the merge conflicts in order for M2 to compile.

> Also, the changes to monomial orderings code were a real conflict, how did you fix that? (When I look, I don't see any mention of changes to monordering.cpp, hpp, which are needed by unit tests).

There were a couple of changes involving files that had moved:
- changes to engine.h were moved to interface/groebner.h, interface/ring.h, and interface/ringelement.h
- changes to x-gb.cpp were moved to interface/groebner.cpp
- changes to x-relem.cpp were split between interface/ring.cpp and interface/ringelement.cpp
- changes to monordering.c/cpp were moved to interface/monomial-ordering.cpp
  - I left the class definition of MonomialOrderings in monordering.hpp, but think eventually it should go to a subdirectory
  - I think some stuff from interface/monomial-ordering.cpp should be moved to something like e/MonomialOrdering as well
- other changes, like matrix.h/cpp were automatically taken care of by git

**Comment by mahrud** [comment]
Also, I just realized the diff on this PR is probably hard to interpret because ncEngine didn't include a bunch of other unrelated pull requests. To limit the diff to only your changes and my changes in the merge, use this link: https://github.com/moorewf/M2-frank/pull/1/files/cbd7cca80b55d071589f77b97a2a3251a4dd2c21..c0c6e4971bdd64b37d0340c7ef826f2007d0acdb

Alternatively, in the diff section, limit to the only last two commits (press shift, click, click)
image

**Pull request merged**
